/*
 * Port_PBcfg.c
 *
 *  Created on: ١٩‏/٠٣‏/٢٠٢٠
 *      Author: JOHN
 */


#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif

/* PB structure used with Port init API */
const Port_ConfigType Port_Configuration =
                                   {
                                		   /* dol el 2 pins el hst3mlhom */
                                		   portConf_BUTTON_PORT_NUMBER,portConf_BUTTON_CHANNEL_NUMBER,portConf_BUTTON_CHANNEL_DIRECTION,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE,
										   portConf_LED_PORT_NUMBER,portConf_LED_CHANNEL_NUMBER,portConf_LED_CHANNEL_DIRECTION,STD_LOW,portConf_LED_CHANNEL_OUTPUT_PIN_MODE,portConf_LED_CHANNEL_DIRECTION_CHANGAEBLE,

										   /* rest of pins */
                                		   portConf_BUTTON_PORT_NUMBER0,portConf_BUTTON_CHANNEL_NUMBER0,portConf_BUTTON_CHANNEL_DIRECTION0,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE0,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE0,
                                		   portConf_BUTTON_PORT_NUMBER1,portConf_BUTTON_CHANNEL_NUMBER1,portConf_BUTTON_CHANNEL_DIRECTION1,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE1,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE1,
                                		   portConf_BUTTON_PORT_NUMBER2,portConf_BUTTON_CHANNEL_NUMBER2,portConf_BUTTON_CHANNEL_DIRECTION2,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE2,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE2,
                                		   portConf_BUTTON_PORT_NUMBER3,portConf_BUTTON_CHANNEL_NUMBER3,portConf_BUTTON_CHANNEL_DIRECTION3,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE3,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE3,
                                		   portConf_BUTTON_PORT_NUMBER4,portConf_BUTTON_CHANNEL_NUMBER4,portConf_BUTTON_CHANNEL_DIRECTION4,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE4,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE4,
                                		   portConf_BUTTON_PORT_NUMBER5,portConf_BUTTON_CHANNEL_NUMBER5,portConf_BUTTON_CHANNEL_DIRECTION5,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE5,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE5,
                                		   portConf_BUTTON_PORT_NUMBER6,portConf_BUTTON_CHANNEL_NUMBER6,portConf_BUTTON_CHANNEL_DIRECTION6,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE6,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE6,
                                		   portConf_BUTTON_PORT_NUMBER7,portConf_BUTTON_CHANNEL_NUMBER7,portConf_BUTTON_CHANNEL_DIRECTION7,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE7,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE7,
                                		   portConf_BUTTON_PORT_NUMBER8,portConf_BUTTON_CHANNEL_NUMBER8,portConf_BUTTON_CHANNEL_DIRECTION8,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE8,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE8,
                                		   portConf_BUTTON_PORT_NUMBER9,portConf_BUTTON_CHANNEL_NUMBER9,portConf_BUTTON_CHANNEL_DIRECTION9,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE9,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE9,
                                		   portConf_BUTTON_PORT_NUMBER10,portConf_BUTTON_CHANNEL_NUMBER10,portConf_BUTTON_CHANNEL_DIRECTION10,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE10,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE10,
                                		   portConf_BUTTON_PORT_NUMBER11,portConf_BUTTON_CHANNEL_NUMBER11,portConf_BUTTON_CHANNEL_DIRECTION11,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE11,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE11,
                                		   portConf_BUTTON_PORT_NUMBER12,portConf_BUTTON_CHANNEL_NUMBER12,portConf_BUTTON_CHANNEL_DIRECTION12,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE12,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE12,
                                		   portConf_BUTTON_PORT_NUMBER13,portConf_BUTTON_CHANNEL_NUMBER13,portConf_BUTTON_CHANNEL_DIRECTION13,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE13,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE13,
                                		   portConf_BUTTON_PORT_NUMBER14,portConf_BUTTON_CHANNEL_NUMBER14,portConf_BUTTON_CHANNEL_DIRECTION14,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE14,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE14,
                                		   portConf_BUTTON_PORT_NUMBER15,portConf_BUTTON_CHANNEL_NUMBER15,portConf_BUTTON_CHANNEL_DIRECTION15,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE15,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE15,
                                		   portConf_BUTTON_PORT_NUMBER16,portConf_BUTTON_CHANNEL_NUMBER16,portConf_BUTTON_CHANNEL_DIRECTION16,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE16,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE16,
                                		   portConf_BUTTON_PORT_NUMBER17,portConf_BUTTON_CHANNEL_NUMBER17,portConf_BUTTON_CHANNEL_DIRECTION17,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE17,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE17,
                                		   portConf_BUTTON_PORT_NUMBER18,portConf_BUTTON_CHANNEL_NUMBER18,portConf_BUTTON_CHANNEL_DIRECTION18,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE18,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE18,
                                		   portConf_BUTTON_PORT_NUMBER19,portConf_BUTTON_CHANNEL_NUMBER19,portConf_BUTTON_CHANNEL_DIRECTION19,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE19,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE19,
                                		   portConf_BUTTON_PORT_NUMBER20,portConf_BUTTON_CHANNEL_NUMBER20,portConf_BUTTON_CHANNEL_DIRECTION20,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE20,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE20,
                                		   portConf_BUTTON_PORT_NUMBER22,portConf_BUTTON_CHANNEL_NUMBER22,portConf_BUTTON_CHANNEL_DIRECTION22,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE22,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE22,
                                		   portConf_BUTTON_PORT_NUMBER23,portConf_BUTTON_CHANNEL_NUMBER23,portConf_BUTTON_CHANNEL_DIRECTION23,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE23,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE23,
                                		   portConf_BUTTON_PORT_NUMBER24,portConf_BUTTON_CHANNEL_NUMBER24,portConf_BUTTON_CHANNEL_DIRECTION24,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE24,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE24,
                                		   portConf_BUTTON_PORT_NUMBER25,portConf_BUTTON_CHANNEL_NUMBER25,portConf_BUTTON_CHANNEL_DIRECTION25,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE25,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE25,
                                		   portConf_BUTTON_PORT_NUMBER27,portConf_BUTTON_CHANNEL_NUMBER27,portConf_BUTTON_CHANNEL_DIRECTION27,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE27,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE27,
                                		   portConf_BUTTON_PORT_NUMBER28,portConf_BUTTON_CHANNEL_NUMBER28,portConf_BUTTON_CHANNEL_DIRECTION28,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE28,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE28,
                                		   portConf_BUTTON_PORT_NUMBER29,portConf_BUTTON_CHANNEL_NUMBER29,portConf_BUTTON_CHANNEL_DIRECTION29,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE29,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE29,
                                		   portConf_BUTTON_PORT_NUMBER30,portConf_BUTTON_CHANNEL_NUMBER30,portConf_BUTTON_CHANNEL_DIRECTION30,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE30,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE30,
                                		   portConf_BUTTON_PORT_NUMBER31,portConf_BUTTON_CHANNEL_NUMBER31,portConf_BUTTON_CHANNEL_DIRECTION31,portConf_BUTTON_CHANNEL_INPUT_PIN_MODE31,STD_LOW,portConf_BUTTON_CHANNEL_DIRECTION_CHANGAEBLE31


                                   };

